version: '3'
services:
  db:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    ports:
      - 5432
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

#  pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "user@mail.ru"
#      PGADMIN_DEFAULT_PASSWORD: "user"
#    ports:
#      - 5050:80
#    depends_on:
#      - db

  eureka:
    image: eureka/web:latest
    ports:
      - 8761:8761
    environment:
      eureka.client.service-url.defaultZone: "http://eureka:8761/eureka"
    command: bash -c "/apps/entrypoint.sh"

  config-server:
    image: config-server/web:latest
    ports:
      - 8888
    environment:
      eureka.client.service-url.defaultZone: "http://eureka:8761/eureka"
    command: bash -c "/apps/wait-for-service.sh eureka 8761 && /apps/entrypoint.sh"

  api:
    image: api/web:latest
    ports:
      - 9090:9090
    environment:
      eureka.client.service-url.defaultZone: "http://eureka:8761/eureka"
    command: bash -c "/apps/wait-for-service.sh config-server 8888 && /apps/entrypoint.sh"

volumes:
  postgres_data_local: